### PR TITLE
Spelling and Grammar correction

### PR DESCRIPTION
**Pull request by skate1512**
I found your repository from the Reddit post, there were some spelling errors so I corrected them.

### CODE REVIEW

**Comment by JoseDeFreitas** [comment]
@skate1512 I've checked your PR. Thank you for this! Should I reopen it?

**Comment by skate1512** [comment]
Github said the PR didn't clear some check so I closed it but you can still see the changes I made so if you want to include them then reopen and merge the PR or just edit the file.

**Comment by JoseDeFreitas** [comment]
As the fork doesn't exist anymore, I can't reopen it. Though, I made the changes manually. There was a problem with the workflows (deleted now). Sorry for the inconvenience. I've mentioned you in the commit message. Thank you a lot for the corrections ✌.

**Comment by skate1512** [comment]
Thanks for the mention, I shouldn't have deleted the fork because of the error.

**Pull request closed without merging**
