### PR TITLE
Added a Youtuber in list

### PR DESCRIPTION
**Pull request by naklic0der**
- Online Tutorials
- Web development
- Web development
- This is the first channel in your list who uploads videos on daily basis ( this makes this channel awesome ). On top of that, it has 1500+ videos already over web dev.

### CODE REVIEW

**Review by JoseDeFreitas — COMMENTED** [review]
Hello @naklic0der!
This channel has indeed a lot of content. The quantity of content influences, but that doesn't make a channel Awesome. Nonetheless, the tutorials are concise and are well designed. There're some changes that need to be made in the layout, but before I want to write about the badge.

Currently, the list has two [badges](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/badges.md): Verified YouTube channel and Weekly content upload. I made those badges so people can know a little more about the channel.
The **verified badge** is somewhat important because you can know a YouTuber has made a lot of work on his channel (at least most of them). [More info here](https://support.google.com/youtube/answer/3046484?hl=en#:~:text=If%20a%20channel%20is%20verified,with%20similar%20names%20on%20YouTube.).
The **weekly upload** badge means that a YouTuber uploads videos weekly. YouTubers that are not active at this moment have still the possibility of being added to the list since it could have awesome video tutorials uploaded. This doesn't mean quality, but if the YouTuber keeps uploading videos on a weekly basis you know it continues uploading a series of videos (playlist); for example.

I like the idea of the badge you're adding, but I think it's too much. Adding this badge means that all the YouTubers that are already in need to be reviewed. Apart from that, is harder to maintain and detect. If a YouTuber uploads videos daily, but suddenly it stops, and then weeks later he starts uploading daily videos again, it should be reviewed for a second time. All come to that the quantity doesn't mean that a YouTuber is awesome. It influences, but it's not determining; it's better to have a channel with few contents but really good explained, made, structured, and so on.

Let me know your thoughts about this! _To be clear, the channel **will** be added after some little changes, just starting this discussion about the badge._

**Comment by naklic0der** [comment]
You are absolutely right! I don't think it is good to keep daily badge...

**Review by JoseDeFreitas — CHANGES_REQUESTED** [review]
Hello @naklic0der! Okay! Thank you for reading my comment. The badge design is great! But just the comment I wrote above. Thank you anyway for that.

Please, put the channel at the bottom of the proper section. This rule is written in order to follow the same rules from the [awesome project](https://github.com/sindresorhus/awesome) and to avoid possible discussions like "why is X YouTuber above X one?": new YouTuber -> bottom of the proper section.

**Comment by naklic0der** [comment]
I have done changes...

**Review by JoseDeFreitas — APPROVED** [review]
Thank you for fixing the change request I made above.
I'm merging. Thank you for adding this awesome YouTuber @naklic0der! 🤗

**Pull request merged**
