### PR TITLE
Machine Learnia > Machine learning

### PR DESCRIPTION
**Pull request by zakarialaoui10**
- **Name of the YouTuber:** Machine Learnia
- **What is the channel about? (eg. web development, design, ...)**: Machine Learning
- **Which section is the channel in? (if you created a section, please specify why)**: Machine Learning
- **Why do you consider the YouTuber deserves a place in this list? *What does make it awesome?***: For me this youtuber succeeded in simplifying machine learning and scikit learn, he used very good editors which are spyder and jupyter notebook...

### CODE REVIEW

**Review by JoseDeFreitas — CHANGES_REQUESTED** [review]
Hello @zakarialaoui10! Thank you for opening this pull request. I reviewed the channel you requested, and he seems that he knows what he's talking about. The tutorials are complete, you can find everything you are looking for.

The main list enumerates only English-speaking YouTubers; there's a folder named “[french](https://github.com/JoseDeFreitas/awesome-youtubers/tree/main/other-languages/french)” that contains [the list for French-speaking YouTubers](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/other-languages/french/readme-fr.md). You should add the channel in that list instead, just below the “Machine learning” section (that is yet not created).

I may reconsider the way channels are ordered... Should all of them be added in the main list with a little flag that indicates its language? I'll think about that. For now, please add the channel to that list. Thank you!

**Comment by JoseDeFreitas** [comment]
Hello again, @zakarialaoui10. I added the channel you requested by myself in the [French-speaking YouTubers list](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/other-languages/french/readme-fr.md). However, I merged your pull request to make sure you appear as a contributor and that you were the one that requested that specific channel. Commit where I manually add the channel: cf97c37d3c2821163c641fbb0dbec47b94c775ea. I think I will probably put all channels in just one file and attach little flags (or language names) right after the channel names, so it's less complicated (though slower) to search for a channel in another language. Thank you!

**Comment by zakarialaoui10** [comment]
Thank you
Sorry , I forgot it because I was too busy

**Comment by zakarialaoui10** [comment]
I checked it , everything is ok

**Comment by JoseDeFreitas** [comment]
Don't worry! Thank you.

**Pull request merged**
